### ISSUE TITLE
YamlPath: plans to publish?

### ISSUE THREAD

**Issue by queil** [fjoppe/Legivel#24]
@fjoppe: I could not find `YamlPath` in the NuGet package. Are you planning to release it at some point? It's a very cool feature indeed. I copied that class to my project for now but I'd rather use it in the *normal* way.

**Comment by fjoppe** [comment]
I wanted to publish YamlPath. But I changed my mind. At least temporary. 

YamlPath has currently two problems:

- a scalar Yaml Node allows characters, which are used to indicate structures in YamlPath, ie I need some sort of escaping, without losing readibility;
- I was working towards a YamlPath mini-language, which provides access to any node in the tree. The hard part is where [mapping keys itself can be a mapping](https://yaml.org/spec/1.2/spec.html#id2763754), which may nest indefinately. Yaml allows this and Legivel too. YamlPath was not meant as an opinionated library, so to support the full Yaml spec. I haven't dug deep enough to check whether this is fully covered.

My strategy was to eliminate both problems organically. With the option to completely change the current chosen mini-language. In current state, it is still very usefull as testing tool. The test's don't require the full-fledged features. To be honest, I haven't worked on it to get published lately. But in current state I would not call it mature.

**Comment by queil** [comment]
@fjoppe Thanks for a detailed explanation. Then for the time being I'll keep using it the way I've started.
