### ISSUE TITLE
Strongname

### ISSUE THREAD

**Issue by johannesvp** [fjoppe/Legivel#29]
### Description

It would be nice to have a version with a strong name / signed version. 

### Related information 
I think it is sufficient to add AssemblyInfo.KeyFile in the AssemblyInfo in the Build.fsx.

**Comment by fjoppe** [comment]
Hi,

Thanks for the suggestion. I've thought of this feature, but didn't get around digging into the details yet. 
I'll have a look into it.

**Comment by fjoppe** [comment]
This is now included in version 0.4.4
https://www.nuget.org/packages/Legivel/0.4.4
