### ISSUE TITLE
Cannot deserialize XML string

### ISSUE THREAD

**Issue by johannesvp** [fjoppe/Legivel#31]
I am trying to deserialize a list of XML strings, but cannot succeed. 

1. Step A
I start of with XML strings like this:
    let xml =
        [ 
          """﻿<XtraSerializer version="1.0" application="DockLayoutManager">"""
          """  <property name="#LayoutVersion" isnull="true" />"""
          """  <property name="$DockLayoutManager" iskey="true" value="DockLayoutManager">"""
          """    <property name="DockingStyle">VS2010</property>"""
          """    <property name="FloatingMode">Desktop</property>"""
          """  </property>"""
          """</XtraSerializer>""" 
        ]

2. Step B
Then I serialize the strings using YamlDotNet, resulting in this YAML document:

- "﻿<XtraSerializer version=\"1.0\" application=\"DockLayoutManager\">"
- "  <property name=\"#LayoutVersion\" isnull=\"true\" />"
- "  <property name=\"$DockLayoutManager\" iskey=\"true\" value=\"DockLayoutManager\">"
- "    <property name=\"DockingStyle\">VS2010</property>"
- "    <property name=\"FloatingMode\">Desktop</property>"
- "  </property>"
- "</XtraSerializer>"
...

3. Step C
I deserialize the YAML document like this:
    Deserialize<string list> yamlDoc

I expect the original strings to be returned. But it returns an error on matching quotes. 
I also tried other options, like single quotes. 

* Operating system: Win10
* Branch v0.4.4
* .NET 4.6.1

**Comment by johannesvp** [comment]
The XML string s are remove when posting the issue: 
`    let xml =
        [ 
          """﻿<XtraSerializer version="1.0" application="DockLayoutManager">"""
          """  <property name="#LayoutVersion" isnull="true" />"""
          """  <property name="$DockLayoutManager" iskey="true" value="DockLayoutManager">"""
          """    <property name="DockingStyle">VS2010</property>"""
          """    <property name="FloatingMode">Desktop</property>"""
          """  </property>"""
          """</XtraSerializer>""" 
        ]
`

**Comment by johannesvp** [comment]
Same for the Yaml document:
`- "﻿<XtraSerializer version=\"1.0\" application=\"DockLayoutManager\">"`
`- "  <property name=\"#LayoutVersion\" isnull=\"true\" />"`
`- "  <property name=\"$DockLayoutManager\" iskey=\"true\" value=\"DockLayoutManager\">"`
`- "    <property name=\"DockingStyle\">VS2010</property>"`
`- "    <property name=\"FloatingMode\">Desktop</property>"`
`- "  </property>"`
`- "</XtraSerializer>"`
`...`

**Comment by fjoppe** [comment]
There is an invisible character - chr(6) - after the first doublequote on the first line.

Compare this:
```fsharp
let goodYaml = "
- \"<XtraSerializer version=\\\"1.0\\\" application=\\\"DockLayoutManager\\\">\"
"

Deserialize<string list> goodYaml
```

With this:
```fsharp
let badYaml = "
- \"﻿<XtraSerializer version=\\\"1.0\\\" application=\\\"DockLayoutManager\\\">\"
"

Deserialize<string list> badYaml
```

Funny thing is, with copy/paste from the web, the issue is included.

In Visual Studio, if you put the cursor between ``"`` and ``<`` and you navigate with the cursor keys left/right, you'll notice it is skipping a character. If you delete the invisible character, the full yaml will parse.

Anyhow, I'd check the source which is generating the Yaml.

**Comment by johannesvp** [comment]
That was the indeed the problem. Thank you very much for finding this. 

Deserializing the XML strings works like a charm.
