### ISSUE TITLE
Output more descriptive errors when deserializing a record with unsupported types

### ISSUE THREAD

**Issue by EverybodyKurts** [fjoppe/Legivel#34]
### Description

Currently, the Legivel library crashes with an arcane error message when encountering a record with a value type it doesn't support. In the below example, the deserializer crashes because the record type is an unsigned integer. The message isn't easy to decipher and doesn't clue me into the fact that the deserializer doesn't like the unsigned integer.

<img width="837" alt="Screen Shot 2021-01-31 at 8 38 47 PM" src="https://user-images.githubusercontent.com/879734/106405488-5bef7a80-6404-11eb-8816-34d8007b1518.png">

### Expected behavior

The following error message like the one below would be nice:

<img width="1080" alt="Screen Shot 2021-01-31 at 8 46 54 PM" src="https://user-images.githubusercontent.com/879734/106405883-99a0d300-6405-11eb-88ba-d4e0cd9ee91b.png">

**Comment by fjoppe** [comment]
Hi,

Thanks for reporting. This is incorrect in different ways:
* uint should be supported
* the error message is arcane - any ``failwith`` statement in the code is for situations I did not expect..

I'm looking into it..

**Comment by fjoppe** [comment]
This has now been fixed and published in version 0.4.6:
https://www.nuget.org/packages/Legivel/0.4.6
