### ISSUE TITLE
Could you please provide a netstandard compatible build

### ISSUE THREAD

**Issue by pkese** [fjoppe/Legivel#7]
Hi,

I'm getting the following when trying to install Legivel into a .net core project
```
warning NU1701: Package 'Legivel 0.2.1' was restored using '.NETFramework,Version=v4.6.1' 
instead of the project target framework '.NETCoreApp,Version=v2.1'.  
This package may not be fully compatible with your project.
```

Is there a reason why this project can't/hasn't been build for .net standard? It doesn't seem there are any specific dependencies specific to classical .net framework.

If not... may I kindly ask you to provide a netstandard compatible build on nuget.

Thanks

**Comment by fjoppe** [comment]
Hi,

A few months ago I tried to prepare this library for .Net Standard. My wish was to support multi-platform from the solution. I got stuck in running the unit-tests in multi-platform mode. Also, Fake was in the middle of a migration, so I decided to wait. But I never got around picking this up again. Help would certainly be appreciated. 
Regards, 
    Frank

**Comment by pkese** [comment]
Yes, I share your experience - I too got bitten by Fake being a running target for a while.
Is your multi-platform code in the `Release_2.2.0` branch? I might give it a look if I find some time to spare...

**Comment by fjoppe** [comment]
The Release_2.2.0 branch is indeed the latest. I ust pushed some stuff in right now so that you can use the latest.

**Comment by fjoppe** [comment]
Currently working on a multi target build in [this branch](https://github.com/fjoppe/Legivel/tree/feature/netstandard-trial2). The build works (on my machine), outputs net45 and netstandard2.0 framework versions. It even runs the unit tests per framework (this cost a lot of time to find out how). Meanwhile I've also made a few performance improvements (ongoing process). 

Still two things are not working:
* Paket has [a defect](https://github.com/fsprojects/Paket/issues/3494), so it can't build a nuget package
* The documentation produced by FSFormatting lists the source script in the page.

**Comment by pkese** [comment]
I'm just wondering: Is the net45 version still necessary if you can provide a netstandard compatible build?
As far as I understand, netstandard compliant DLL can be used seamlessly in both netcore and net-framework style projects.

**Comment by fjoppe** [comment]
It would be ok to provide both. Maybe I'm doing something wrong. But my experience with linking .netstandard libararies into the FSI in Visual Studio has caused me quite some troubles. net45 libs were easier to reference. And my assesment for using a library is the observation whether the lib is "close" to the framework I'm using. So providing multi-platform helps build  confidence, but that is self-projection.  :)

Still working on this enhancement. Have not heard from FSDocumentation whether they will solve my issue, And in the meanwhile I'm implementing a new Regex algorithmn to improve performance.

**Comment by fjoppe** [comment]
Hi,

I have released a new version of this package [Legivel 0.3.0](https://www.nuget.org/packages/Legivel/0.3.0) which includes a netstandard binary. Also did some work to make it faster, but not satisfied yet in the latter topic.

**Comment by pkese** [comment]
Thanks, Frank. You rock! It works beautifully.  
I assume we can now close this ticket - performance is probably orthogonal to this issue, no?

**Comment by fjoppe** [comment]
Yes it can be closed.

Regards,
    Frank


Verstuurd vanaf mijn iPhone

Op 6 mei 2019 om 13:43 heeft Peter Keše <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Thanks, Frank. You rock! It works beautifully.
I assume we can now close this ticket - performance is probably orthogonal to this issue, no?
